### 
POST http://localhost:8080/api/account/register

{
    "email": "email1@gmail.com",
    "password": "123456t",
    "confirmPassword": "123456t",
    "firstName": "Thuong",
    "lastName": "Thuong",
    "authenWith": 2
}
###
