version: "3.8"

services:
  app:
    build: .
    container_name: itenv-server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://localhost:27017/DevArticlesDB"

  mongodb:
    image: mongo:6.0
    container_name: mongo-db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
