app = "itenv-server"  # tên app trên Fly bạn đã tạo (chính xác chưa? nhớ chạy fly apps list kiểm tra)
primary_region = "sgp"  # Singapore region (đúng ký hiệu rồi)

[env]
MONGODB_URI = "mongodb+srv://trinhngocthuong17523:1234567890@cluster0.iblhqgw.mongodb.net/ITenvDB?retryWrites=true&w=majority&appName=Cluster0"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
