export enum ApiUsers {
    CURRENT_USER = '/current',
    ALL_USERS = '',
    ALL_FRIENDS = '/friends',
    ALL_USERS_FRIENDPAGE = '/friend-page',
    SINGLE_USER_BY_ID = '/:userId',
    EDIT_MYPROFILE = '',
    EDIT_AVATAR = '/avatar',
    USER_DETAIL = '/detail',
    NEW_USER_BY_MONTH = '/new/month',
    NEW_USER_TODAY = '/new/today',
    CHURN_USER_RATE = '/percent/churn-rate',
    TOTAL_USER = '/total',
    TOTAL_ACTIVE = '/total/active',
    USER_GROWTH = '/growth',
    USER_DEMOGRAPHICS = '/demographics',
    SOLVER_PROBLEMS = '/solver',
}